import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    // Splash & Login
    appName: 'SideQuest',
    appSuffix: '.Tourism',
    tagline: "Discover Brunei's Heritage",
    loginAs: 'Login as',
    touristLogin: 'Tourist Login',
    hostLogin: 'MSME Host Login',
    welcomeBack: 'Welcome back',
    enterAsTourist: '🌏 Enter as Tourist',
    enterAsHost: '🏛️ Enter as MSME Host',
    logout: 'Logout',

    // Passport Scanner
    passportScan: 'Passport Scan',
    scanPassport: 'Scan Your Passport',
    scanInstructions: 'Position your passport within the frame',
    scanning: 'Scanning...',
    scanComplete: 'Scan Complete',
    passportVerified: 'Passport Verified',
    continue: 'Continue',
    name: 'Name',
    nationality: 'Nationality',
    passportNo: 'Passport No.',

    // Face Selfie
    faceSelfie: 'Face Verification',
    positionFace: 'Position your face within the circle',
    capturing: 'Capturing...',
    verifying: 'Verifying biometrics...',
    faceVerified: 'Face Verified',
    matchScore: 'Match Score',

    // Nav
    explore: 'Explore',
    bookings: 'Bookings',
    inbox: 'Inbox',
    pocket: 'Pocket',
    profile: 'Profile',
    home: 'Home',
    requests: 'Requests',
    wallet: 'Wallet',
    scanner: 'Scanner',
    schedule: 'Schedule',

    // Dashboard
    searchActivities: 'Search local activities...',
    exploreBrunei: 'Explore Brunei',
    availableValue: 'Available Value',
    geofence: 'Geofence',
    heritageExperiences: 'Heritage Experiences nearby',
    viewActivity: 'View Activity',

    // Booking
    bookAndLock: 'Book & Lock Funds',
    date: 'Date',
    timeSlot: 'Time Slot',
    participants: 'Participants',
    grossTotal: 'Gross Total (BND)',
    description: 'Description',
    location: 'Location',
    duration: 'Duration',
    minutes: 'Minutes',
    perPerson: 'per person',

    // Categories
    all: 'All',
    culture: 'Culture',
    adventure: 'Adventure',
    food: 'Food',
    nature: 'Nature',

    // Payment
    paymentMethod: 'Payment Method',
    escrowWallet: 'Escrow Wallet',
    cardPayment: 'Card Payment',
    cardNumber: 'Card Number',
    expiry: 'Expiry',
    cvv: 'CVV',
    payNow: 'Pay Now',
    processing: 'Processing...',
    paymentSuccess: 'Payment Successful',

    // QR & Tickets
    myTickets: 'My Tickets',
    viewTicket: 'View QR Ticket',
    downloadTicket: 'Download Ticket',
    ticketId: 'Ticket ID',
    validFor: 'Valid for',
    guests: 'Guests',
    achievements: 'Achievements',
    firstBooking: 'First Booking',
    explorer: 'Explorer',
    veteran: 'Veteran Traveler',

    // Scheduler
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    available: 'Available',
    booked: 'Booked',

    // Host Portal
    hostPortal: 'MSME Host Portal',
    netEarnings: 'Net Earnings',
    activeBookings: 'Active Bookings',
    myOfferings: 'My Heritage Offerings',
    active: 'active',
    profileStudio: 'Profile Studio',
    createActivity: 'Create Activity',
    compliance: 'Compliance',
    qrScanner: 'QR Scanner',
    availability: 'Availability',
    cashOut: 'Cash Out',

    // BruneiID
    bruneiIdAuth: 'BruneiID Verification',
    scanFingerprint: 'Place your finger on the sensor',
    authenticating: 'Authenticating with BruneiID...',
    identityVerified: 'Identity Verified',
    bruneiIdLinked: 'BruneiID Successfully Linked',

    // Profile Studio
    editProfile: 'Edit Profile',
    businessName: 'Business Name',
    businessDesc: 'Business Description',
    contactInfo: 'Contact Information',
    saveProfile: 'Save Profile',
    verified: 'Verified',
    rating: 'Rating',

    // Activity Creator
    createNewActivity: 'Create New Activity',
    basicInfo: 'Basic Info',
    pricing: 'Pricing',
    activityTitle: 'Activity Title',
    category: 'Category',
    district: 'District',
    exactLocation: 'Exact Location',
    pricePerPerson: 'Price per Person (BND)',
    maxParticipants: 'Max Participants',
    durationMinutes: 'Duration (minutes)',
    publishActivity: 'Publish Activity',

    // Availability Calendar
    availabilityCalendar: 'Availability Calendar',
    capacityPerSlot: 'Capacity per slot',
    blocked: 'Blocked',
    toggleAvailability: 'Tap to toggle availability',

    // Compliance
    complianceDocs: 'Compliance Documents',
    uploadDoc: 'Upload Document',
    businessLicense: 'Business License',
    insuranceCert: 'Insurance Certificate',
    safetyPermit: 'Safety Permit',
    pending: 'Pending Review',
    approved: 'Approved',
    rejected: 'Rejected',
    required: 'Required',

    // QR Scanner
    scanTicket: 'Scan Tourist Ticket',
    pointCamera: 'Point camera at QR code',
    ticketValid: 'Ticket Valid ✓',
    ticketInvalid: 'Invalid Ticket ✗',
    scanHistory: 'Scan History',

    // Wallet
    withdrawToBank: 'Withdraw to Bank',
    whitelistedAccounts: 'Whitelisted Accounts',
    addAccount: 'Add Account',
    confirmWithdrawal: 'Confirm Withdrawal',
    transferSuccess: 'Transfer Success',
    passport: 'Passport',
    digitalPassport: 'Digital Passport',
    recommendedForYou: 'Recommended for You',
  },

  ms: {
    appName: 'SideQuest',
    appSuffix: '.Pelancongan',
    tagline: 'Terokai Warisan Brunei',
    loginAs: 'Log masuk sebagai',
    touristLogin: 'Log Masuk Pelancong',
    hostLogin: 'Log Masuk Hos MSME',
    welcomeBack: 'Selamat kembali',
    enterAsTourist: '🌏 Masuk sebagai Pelancong',
    enterAsHost: '🏛️ Masuk sebagai Hos MSME',
    logout: 'Log keluar',
    passportScan: 'Imbasan Pasport',
    scanPassport: 'Imbas Pasport Anda',
    scanInstructions: 'Letakkan pasport dalam bingkai',
    scanning: 'Mengimbas...',
    scanComplete: 'Imbasan Selesai',
    passportVerified: 'Pasport Disahkan',
    continue: 'Teruskan',
    name: 'Nama',
    nationality: 'Kewarganegaraan',
    passportNo: 'No. Pasport',
    faceSelfie: 'Pengesahan Wajah',
    positionFace: 'Letakkan wajah anda dalam bulatan',
    capturing: 'Menangkap...',
    verifying: 'Mengesahkan biometrik...',
    faceVerified: 'Wajah Disahkan',
    matchScore: 'Skor Padanan',
    explore: 'Terokai',
    bookings: 'Tempahan',
    inbox: 'Peti Masuk',
    pocket: 'Dompet',
    profile: 'Profil',
    home: 'Utama',
    requests: 'Permintaan',
    wallet: 'Dompet',
    scanner: 'Pengimbas',
    schedule: 'Jadual',
    searchActivities: 'Cari aktiviti tempatan...',
    exploreBrunei: 'Terokai Brunei',
    availableValue: 'Nilai Tersedia',
    geofence: 'Geofence',
    heritageExperiences: 'Pengalaman Warisan berdekatan',
    viewActivity: 'Lihat Aktiviti',
    bookAndLock: 'Tempah & Kunci Dana',
    date: 'Tarikh',
    timeSlot: 'Slot Masa',
    participants: 'Peserta',
    grossTotal: 'Jumlah Kasar (BND)',
    description: 'Penerangan',
    location: 'Lokasi',
    duration: 'Tempoh',
    minutes: 'Minit',
    perPerson: 'seorang',
    all: 'Semua',
    culture: 'Budaya',
    adventure: 'Pengembaraan',
    food: 'Makanan',
    nature: 'Alam',
    paymentMethod: 'Kaedah Pembayaran',
    escrowWallet: 'Dompet Escrow',
    cardPayment: 'Pembayaran Kad',
    cardNumber: 'Nombor Kad',
    expiry: 'Tamat Tempoh',
    cvv: 'CVV',
    payNow: 'Bayar Sekarang',
    processing: 'Memproses...',
    paymentSuccess: 'Pembayaran Berjaya',
    myTickets: 'Tiket Saya',
    viewTicket: 'Lihat Tiket QR',
    downloadTicket: 'Muat Turun Tiket',
    ticketId: 'ID Tiket',
    validFor: 'Sah untuk',
    guests: 'Tetamu',
    achievements: 'Pencapaian',
    firstBooking: 'Tempahan Pertama',
    explorer: 'Penjelajah',
    veteran: 'Pelancong Veteran',
    selectDate: 'Pilih Tarikh',
    selectTime: 'Pilih Masa',
    available: 'Tersedia',
    booked: 'Ditempah',
    hostPortal: 'Portal Hos MSME',
    netEarnings: 'Pendapatan Bersih',
    activeBookings: 'Tempahan Aktif',
    myOfferings: 'Tawaran Warisan Saya',
    active: 'aktif',
    profileStudio: 'Studio Profil',
    createActivity: 'Cipta Aktiviti',
    compliance: 'Pematuhan',
    qrScanner: 'Pengimbas QR',
    availability: 'Ketersediaan',
    cashOut: 'Pengeluaran',
    bruneiIdAuth: 'Pengesahan BruneiID',
    scanFingerprint: 'Letakkan jari pada sensor',
    authenticating: 'Mengesahkan dengan BruneiID...',
    identityVerified: 'Identiti Disahkan',
    bruneiIdLinked: 'BruneiID Berjaya Dipautkan',
    editProfile: 'Edit Profil',
    businessName: 'Nama Perniagaan',
    businessDesc: 'Penerangan Perniagaan',
    contactInfo: 'Maklumat Hubungan',
    saveProfile: 'Simpan Profil',
    verified: 'Disahkan',
    rating: 'Penilaian',
    createNewActivity: 'Cipta Aktiviti Baharu',
    basicInfo: 'Info Asas',
    pricing: 'Harga',
    activityTitle: 'Tajuk Aktiviti',
    category: 'Kategori',
    district: 'Daerah',
    exactLocation: 'Lokasi Tepat',
    pricePerPerson: 'Harga Seorang (BND)',
    maxParticipants: 'Peserta Maksimum',
    durationMinutes: 'Tempoh (minit)',
    publishActivity: 'Terbitkan Aktiviti',
    availabilityCalendar: 'Kalendar Ketersediaan',
    capacityPerSlot: 'Kapasiti setiap slot',
    blocked: 'Disekat',
    toggleAvailability: 'Ketik untuk tukar ketersediaan',
    complianceDocs: 'Dokumen Pematuhan',
    uploadDoc: 'Muat Naik Dokumen',
    businessLicense: 'Lesen Perniagaan',
    insuranceCert: 'Sijil Insurans',
    safetyPermit: 'Permit Keselamatan',
    pending: 'Dalam Semakan',
    approved: 'Diluluskan',
    rejected: 'Ditolak',
    required: 'Diperlukan',
    scanTicket: 'Imbas Tiket Pelancong',
    pointCamera: 'Halakan kamera ke kod QR',
    ticketValid: 'Tiket Sah ✓',
    ticketInvalid: 'Tiket Tidak Sah ✗',
    scanHistory: 'Sejarah Imbasan',
    withdrawToBank: 'Pengeluaran ke Bank',
    whitelistedAccounts: 'Akaun Senarai Putih',
    addAccount: 'Tambah Akaun',
    confirmWithdrawal: 'Sahkan Pengeluaran',
    transferSuccess: 'Pemindahan Berjaya',
    passport: 'Pasport',
    digitalPassport: 'Pasport Digital',
    recommendedForYou: 'Disyorkan untuk Anda',
  },

  zh: {
    appName: 'SideQuest',
    appSuffix: '.旅游',
    tagline: '探索文莱遗产',
    loginAs: '登录为',
    touristLogin: '游客登录',
    hostLogin: 'MSME主机登录',
    welcomeBack: '欢迎回来',
    enterAsTourist: '🌏 游客入口',
    enterAsHost: '🏛️ MSME主机入口',
    logout: '退出',
    passportScan: '护照扫描',
    scanPassport: '扫描您的护照',
    scanInstructions: '将护照放在框架内',
    scanning: '扫描中...',
    scanComplete: '扫描完成',
    passportVerified: '护照已验证',
    continue: '继续',
    name: '姓名',
    nationality: '国籍',
    passportNo: '护照号码',
    faceSelfie: '面部验证',
    positionFace: '将面部对准圆圈',
    capturing: '捕捉中...',
    verifying: '验证生物信息...',
    faceVerified: '面部已验证',
    matchScore: '匹配分数',
    explore: '探索',
    bookings: '预订',
    inbox: '消息',
    pocket: '钱包',
    profile: '个人',
    home: '首页',
    requests: '请求',
    wallet: '钱包',
    scanner: '扫描',
    schedule: '日程',
    searchActivities: '搜索当地活动...',
    exploreBrunei: '探索文莱',
    availableValue: '可用价值',
    geofence: '地理围栏',
    heritageExperiences: '附近的遗产体验',
    viewActivity: '查看活动',
    bookAndLock: '预订并锁定资金',
    date: '日期',
    timeSlot: '时间段',
    participants: '参与者',
    grossTotal: '总计 (BND)',
    description: '描述',
    location: '位置',
    duration: '时长',
    minutes: '分钟',
    perPerson: '每人',
    all: '全部',
    culture: '文化',
    adventure: '冒险',
    food: '美食',
    nature: '自然',
    paymentMethod: '支付方式',
    escrowWallet: '托管钱包',
    cardPayment: '银行卡支付',
    cardNumber: '卡号',
    expiry: '有效期',
    cvv: 'CVV',
    payNow: '立即支付',
    processing: '处理中...',
    paymentSuccess: '支付成功',
    myTickets: '我的门票',
    viewTicket: '查看QR门票',
    downloadTicket: '下载门票',
    ticketId: '门票ID',
    validFor: '有效期',
    guests: '客人',
    achievements: '成就',
    firstBooking: '首次预订',
    explorer: '探索者',
    veteran: '资深旅行者',
    selectDate: '选择日期',
    selectTime: '选择时间',
    available: '可用',
    booked: '已预订',
    hostPortal: 'MSME主机门户',
    netEarnings: '净收入',
    activeBookings: '活跃预订',
    myOfferings: '我的遗产项目',
    active: '活跃',
    profileStudio: '档案工作室',
    createActivity: '创建活动',
    compliance: '合规',
    qrScanner: 'QR扫描',
    availability: '可用性',
    cashOut: '提现',
    bruneiIdAuth: 'BruneiID验证',
    scanFingerprint: '将手指放在传感器上',
    authenticating: '正在通过BruneiID验证...',
    identityVerified: '身份已验证',
    bruneiIdLinked: 'BruneiID成功关联',
    editProfile: '编辑档案',
    businessName: '企业名称',
    businessDesc: '企业描述',
    contactInfo: '联系信息',
    saveProfile: '保存档案',
    verified: '已验证',
    rating: '评分',
    createNewActivity: '创建新活动',
    basicInfo: '基本信息',
    pricing: '定价',
    activityTitle: '活动标题',
    category: '类别',
    district: '地区',
    exactLocation: '精确位置',
    pricePerPerson: '每人价格 (BND)',
    maxParticipants: '最大参与人数',
    durationMinutes: '时长（分钟）',
    publishActivity: '发布活动',
    availabilityCalendar: '可用日历',
    capacityPerSlot: '每个时段容量',
    blocked: '已屏蔽',
    toggleAvailability: '点击切换可用性',
    complianceDocs: '合规文档',
    uploadDoc: '上传文档',
    businessLicense: '营业执照',
    insuranceCert: '保险证书',
    safetyPermit: '安全许可',
    pending: '审核中',
    approved: '已批准',
    rejected: '已拒绝',
    required: '必需',
    scanTicket: '扫描游客门票',
    pointCamera: '将相机对准QR码',
    ticketValid: '门票有效 ✓',
    ticketInvalid: '无效门票 ✗',
    scanHistory: '扫描历史',
    withdrawToBank: '提款到银行',
    whitelistedAccounts: '白名单账户',
    addAccount: '添加账户',
    confirmWithdrawal: '确认提款',
    transferSuccess: '转账成功',
    passport: '护照',
    digitalPassport: '数字护照',
    recommendedForYou: '推荐给您',
  }
};

const detectBrowserLocale = () => {
  const lang = navigator.language || navigator.languages?.[0] || 'en';
  if (lang.startsWith('ms') || lang.startsWith('my')) return 'ms';
  if (lang.startsWith('zh')) return 'zh';
  return 'en';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('sq_tourism_lang');
    return saved || detectBrowserLocale();
  });

  useEffect(() => {
    localStorage.setItem('sq_tourism_lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const cycleLanguage = () => {
    const langs = ['en', 'ms', 'zh'];
    const idx = langs.indexOf(language);
    setLanguage(langs[(idx + 1) % langs.length]);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, cycleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
